
server:
  port: 18080
  servlet:
    context-path: /polbot
spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/uplus_chatbot?autoReconnect=true
#    username: root
#    password: chmp1985!@
#    driver-class-name: com.mysql.jdbc.Driver
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp



logging:
  config: classpath:logback.xml
  file:
    path: logs

